CREATE TABLE CATEGORIA(
	CodCategoria INTEGER NOT NULL,
	Descricao VARCHAR(80),
	PRIMARY KEY ("CodCategoria")
);



SELECT CodLancamento FROM LANCAMENTO WHERE CodLancamento = 1;


CREATE TABLE CATEGORIA(
	CodCategoria INTEGER NOT NULL,
	Descricao VARCHAR(80),
	PRIMARY KEY ("CodCategoria")
);


INSERT INTO 

DELETE FROM PARCELADO WHERE CODLANCAMENTO = 4